@startuml
left to right direction
actor Admin
actor "Medical Staff" as Staff
left to right direction

rectangle "EMR System" {
    Admin --> (Access Medical History) : Select Option
    Staff --> (Access Medical History) : Select Option
    (Access Medical History) --> (Enter Patient ID)
    (Enter Patient ID) --> (Retrieve Medical History)
    (Retrieve Medical History) --> Admin : Display Medical History
    (Retrieve Medical History) --> Staff : Display Medical History
    (Retrieve Medical History) --> (Retrieve Billing History) : Sync with Financial System
    (Retrieve Billing History) --> Admin : Display Billing Info
    (Retrieve Billing History) --> Staff : Display Billing Info

    rectangle "Alternate Scenarios" {
        (Patient Not Found) <.. (Enter Patient ID) : Notify Error
    }
}
@enduml
